#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0

function jupiter_biosupdate {
  logger "info: Jupiter BIOS update called: $@"

  # Always return success.
  return 0
}

jupiter_biosupdate "$@"
